name: CI-fizz-buzz

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker container
        run:  make build
      - name: Start docker-compose
        run: make start
      - name: Composer install
        run: make prepare
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60' # for 60 seconds
      - name: Create test database
        run: make create-database-test
      - run: docker ps
      - name: Execute test
        run: make test
